version: '3.4'

services:
  ecommerce.data:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    hostname: rabbit
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  carrinho.api:
    image: carrinhoapi
    build:
      context: .
      dockerfile: CasaDoCodigo.Carrinho/Dockerfile
    depends_on:
      - rabbitmq

  catalogo.api:
    image: catalogoapi
    build:
      context: .
      dockerfile: CasaDoCodigo.Catalogo/Dockerfile


  identity.api:
    image: identityapi
    build:
      context: .
      dockerfile: CasaDoCodigo.Identity/Dockerfile
    depends_on:
      - rabbitmq

  ordemdecompra.api:
    image: ordemdecompraapi
    build:
      context: .
      dockerfile: OrdemDeCompra.API/Dockerfile
    depends_on:
      - rabbitmq

  mvc:
    image: mvc
    build:
      context: .
      dockerfile: CasaDoCodigo.CQRS/Dockerfile
    depends_on:
      - ecommerce.data
